-- CONSULTA COM GROUPY BY E HAVING --
-- PROJETAR OS PROTAGONISTAS QUE TEM MAIS DE 3 MORTES --
SELECT NOME_PROTAGONISTA
FROM MATA
GROUP BY NOME_PROTAGONISTA
HAVING COUNT(*) > 3;

-- CONSULTA COM INNER JOIN --
-- PROJETAR O NOME DO PROTAGONISTA, A MISSÃO E O VEÍCULO QUE ELE DIRIGIU -- 
SELECT p.NOME, d.DESCRICAO, v.NOME AS NOME_VEICULO
FROM DIRIGE d
INNER JOIN PROTAGONISTA p ON p.NOME = d.NOME_PROTAGONISTA 
INNER JOIN VEICULO v ON v.NOME = d.NOME_VEICULO;


-- CONSULTA COM OUTER JOIN --
-- PROJETA PESSOAS QUE NÃO PERTENCEM A NENHUMA GANGUE -- 
SELECT P.NOME
FROM PESSOA P
LEFT OUTER JOIN MEMBRO M
ON P.NOME = M.NOME_PESSOA
WHERE M.NOME_GANGUE IS NULL;

-- CONSULTA COM SEMI JUNÇÃO --
-- PROJETA OS VEÍCULOS QUE TOCAM ALGUMA MÚSICA --
SELECT V.NOME
FROM VEICULO V
WHERE EXISTS (SELECT *
              FROM TOCA T
              WHERE T.NOME_VEICULO = V.NOME);

-- CONSULTA COM ANTI-JOIN --
-- PROJETA NPCS QUE NÃO FORAM MORTOS POR NENHUM PROTAGONISTA --
SELECT N.NOME
FROM NPC N
WHERE NOT EXISTS (
    SELECT *
    FROM MATA M
    WHERE M.NOME_NPC = N.NOME);


-- SUBCONSULTA DO TIPO ESCALAR --
-- PROJETA O PROTAGONISTA COM O MAIOR NÚMERO DE MORTES --
SELECT NOME_PROTAGONISTA
FROM MATA
GROUP BY NOME_PROTAGONISTA
HAVING COUNT(*) = (
    SELECT MAX(COUNT(*))
    FROM MATA
    GROUP BY NOME_PROTAGONISTA);

-- SUBCONSULTA DO TIPO LINHA -- 
-- PROJETA MISSÃO COM MAIOR RECOMPENSA;
SELECT DESCRICAO, RECOMPENSA
FROM MISSAO
WHERE RECOMPENSA = (SELECT MAX(RECOMPENSA)
                    FROM MISSAO);

-- SUBCONSULTA DO TIPO TABELA --
-- PROJETA TODOS OS VEICÚLOS QUE TOCAM DETERMINADA MÚSICA --
SELECT NOME
FROM VEICULO
WHERE NOME IN (SELECT NOME_VEICULO
               FROM TOCA
               WHERE NOME_MUSICA = 'CJSong');


-- OPERAÇÃO DE CONJUNTO --
-- PROJETA OS NPCS MORTOS PELOS PROTAGONISTAS CJ E TOMMY  --
SELECT NOME_NPC
FROM MATA
WHERE NOME_PROTAGONISTA = 'Carl'
INTERSECT
SELECT NOME_NPC
FROM MATA
WHERE NOME_PROTAGONISTA = 'Tommy';
